### ISSUE TITLE
获取头像为undefined

### ISSUE THREAD

**Issue by axlmly** [dingyi222666/koishi-plugin-better-custom-welcome-message#1]
session Error: Error with request send_group_msg, args: {"group_id":623987016,"message":[{"type":"text","data":{"text":"旅行者"}},{"type":"at","data":{"qq":"3034005821"}},{"type":"text","data":{"text":" 你醒啦nya？现在时间是 2024/5/16 12:23:20 nya！\n"}},{"type":"image","data":{"file":"undefined","cache":0}},{"type":"text","data":{"text":" \n从你睡着后发生了很多事nya……\n不记得了也没事nya！\n新人你好nya！同新握爪nya！"}}]}, retcode: 1200
                            at Internal._get (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\types.js:44:15)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async Internal.<computed> [as sendGroupMsg] (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\types.js:84:26)
                            at async OneBotMessageEncoder.flush (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\bot\message.js:95:24)
                            at async OneBotMessageEncoder.send (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:569:5)
                            at async Proxy.sendMessage (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:328:22)
                            at async Proxy.<anonymous> (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-better-custom-welcome-message\lib\index.js:72:9)
退群消息没有动静

![chrome_4d47VQkn6f](https://github.com/dingyi222666/koishi-plugin-better-custom-welcome-message/assets/41771421/4ba2547d-4913-4e32-be2b-5e9aa170cc6f)

**Comment by dingyi222666** [comment]
新版本 koishi 退群消息应该可用了.
头像问题目前给 one-adapter, red-adapter 尝试添加了头像获取.

你也可以填写一个头像 url 的模板,这适用于所有的可接入 QQ (的能获取到群成员 ID的)适配器:
```
![?](https://q.qlogo.cn/headimg_dl?dst_uin={id}&spec=640)
```
