### ISSUE TITLE
疑似使用人多导致的一言API Forbidden错误

### ISSUE THREAD

**Issue by wq5794250** [dingyi222666/koishi-plugin-better-custom-welcome-message#7]
```
Error: Forbidden
                            at [cordis.invoke] (/koishi/node_modules/@cordisjs/plugin-http/lib/index.cjs:340:23)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async Proxy.<anonymous> (/koishi/node_modules/@cordisjs/plugin-http/lib/index.cjs:178:26)
                            at async hitokoto (/koishi/node_modules/koishi-plugin-better-custom-welcome-message/lib/index.cjs:199:24)
                            at async formatMessage (/koishi/node_modules/koishi-plugin-better-custom-welcome-message/lib/index.cjs:131:355)
                            at async Proxy.<anonymous> (/koishi/node_modules/koishi-plugin-better-custom-welcome-message/lib/index.cjs:87:24)
```

403导致发送不了欢迎信息
-
还希望加入多份配置功能以配置不同群使用不通的欢迎消息

**Comment by wq5794250** [comment]
注明：使用的欢迎消息未用到{hitokoto}变量还是会导致Forbidden引发无法欢迎的问题

**Comment by dingyi222666** [comment]
不应该啊，去掉一言字段应该正常了啊



---Original---
From: ***@***.***&gt;
Sent at: 2024年12月20日(Fri) Evening10:27
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [dingyi222666/koishi-plugin-better-custom-welcome-message] 疑似使用人多导致的一言API Forbidden错误 (Issue #7)




 
注明：使用的欢迎消息未用到{hitokoto}变量还是会导致Forbidden引发无法欢迎的问题

**Comment by dingyi222666** [comment]
已经原生支持多配置了噢，选择器可以针对不同群设置不同的欢迎消息索引，这些都是写在 readme 里面的

---Original---
From: ***@***.***&gt;
Sent at: 2024年12月20日(Fri) Evening10:24
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [dingyi222666/koishi-plugin-better-custom-welcome-message] 疑似使用人多导致的一言API403 (Issue #7)




 Error: Forbidden                             at [cordis.invoke] ***@***.***/plugin-http/lib/index.cjs:340:23)                             at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                             at async Proxy.<anonymous&gt; ***@***.***/plugin-http/lib/index.cjs:178:26)                             at async hitokoto (/koishi/node_modules/koishi-plugin-better-custom-welcome-message/lib/index.cjs:199:24)                             at async formatMessage (/koishi/node_modules/koishi-plugin-better-custom-welcome-message/lib/index.cjs:131:355)                             at async Proxy.<anonymous&gt; (/koishi/node_modules/koishi-plugin-better-custom-welcome-message/lib/index.cjs:87:24)  
403导致发送不了欢迎信息
 
还希望加入多份配置功能以配置不同群使用不通的欢迎消息

**Comment by dingyi222666** [comment]
我测试这边一言 API 完全正常触发啊

**Comment by wq5794250** [comment]
沙盒中测试多份插件配置时报错：

```
app Error: duplicate plugin detected: better-custom-welcome-message
                            at Proxy.plugin (/koishi/node_modules/@cordisjs/core/lib/index.cjs:1058:57)
                            at Proxy.forkPlugin (/koishi/node_modules/@koishijs/loader/lib/shared.js:279:19)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async Proxy.reload (/koishi/node_modules/@koishijs/loader/lib/shared.js:306:16)
                            at async ConfigWriter.reload (/koishi/node_modules/@koishijs/plugin-config/lib/shared/index.js:263:5)
                            at async ConfigWriter.ctx.console.addListener.authority (/koishi/node_modules/@koishijs/plugin-config/lib/shared/index.js:188:11)
                            at async WebSocket.receive (/koishi/node_modules/@koishijs/plugin-console/node_modules/@koishijs/console/lib/index.js:127:21)
2024-12-22 19:39:44 [W] sqlite > INSERT INTO `binding` (`aid`, `bid`, `pid`, `platform`) VALUES (?, ?, ?, ?) [ 235, 235, 'Carol', 'sandbox:oz5airtc0ql' ]
2024-12-22 19:39:44 [W] app TypeError: Cannot read properties of undefined (reading 'operator_id')
                            at /koishi/node_modules/koishi-plugin-star-security/lib/index.js:205:14
                            at Object.apply (/koishi/node_modules/@cordisjs/core/lib/index.cjs:417:23)
                            at Proxy.dispatch (/koishi/node_modules/@cordisjs/core/lib/index.cjs:514:27)
                            at dispatch.next (<anonymous>)
                            at Function.from (<anonymous>)
                            at Proxy.emit (/koishi/node_modules/@cordisjs/core/lib/index.cjs:521:11)
                            at ctx.console.addListener.authority (/koishi/node_modules/@koishijs/plugin-sandbox/lib/index.js:244:11)
                            at Object.apply (/koishi/node_modules/@cordisjs/core/lib/index.cjs:171:28)
                            at WebSocket.receive (/koishi/node_modules/@koishijs/plugin-console/node_modules/@koishijs/console/lib/index.js:127:45)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-12-22 19:40:35 [W] sqlite > INSERT INTO `binding` (`aid`, `bid`, `pid`, `platform`) VALUES (?, ?, ?, ?) [ 237, 237, 'Dave', 'sandbox:oz5airtc0ql' ]
2024-12-22 19:40:35 [W] app TypeError: Cannot read properties of undefined (reading 'operator_id')
                            at /koishi/node_modules/koishi-plugin-star-security/lib/index.js:205:14
                            at Object.apply (/koishi/node_modules/@cordisjs/core/lib/index.cjs:417:23)
                            at Proxy.dispatch (/koishi/node_modules/@cordisjs/core/lib/index.cjs:514:27)
                            at dispatch.next (<anonymous>)
                            at Function.from (<anonymous>)
                            at Proxy.emit (/koishi/node_modules/@cordisjs/core/lib/index.cjs:521:11)
                            at ctx.console.addListener.authority (/koishi/node_modules/@koishijs/plugin-sandbox/lib/index.js:244:11)
                            at Object.apply (/koishi/node_modules/@cordisjs/core/lib/index.cjs:171:28)
                            at WebSocket.receive (/koishi/node_modules/@koishijs/plugin-console/node_modules/@koishijs/console/lib/index.js:127:45)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-12-22 19:40:55 [I] loader unload plugin better-custom-welcome-message:dcb7pn
2024-12-22 19:40:59 [W] sqlite > INSERT INTO `binding` (`aid`, `bid`, `pid`, `platform`) VALUES (?, ?, ?, ?) [ 239, 239, 'Eve', 'sandbox:oz5airtc0ql' ]
2024-12-22 19:40:59 [W] app TypeError: Cannot read properties of undefined (reading 'operator_id')
                            at /koishi/node_modules/koishi-plugin-star-security/lib/index.js:205:14
                            at Object.apply (/koishi/node_modules/@cordisjs/core/lib/index.cjs:417:23)
                            at Proxy.dispatch (/koishi/node_modules/@cordisjs/core/lib/index.cjs:514:27)
                            at dispatch.next (<anonymous>)
                            at Function.from (<anonymous>)
                            at Proxy.emit (/koishi/node_modules/@cordisjs/core/lib/index.cjs:521:11)
                            at ctx.console.addListener.authority (/koishi/node_modules/@koishijs/plugin-sandbox/lib/index.js:244:11)
                            at Object.apply (/koishi/node_modules/@cordisjs/core/lib/index.cjs:171:28)
                            at WebSocket.receive (/koishi/node_modules/@koishijs/plugin-console/node_modules/@koishijs/console/lib/index.js:127:45)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

并且koishi说明该插件无法多份配置
![3681f6f5f1fb9863ece0b40c743b006e](https://github.com/user-attachments/assets/03dbcefe-148a-469f-98ac-aca9cc843343)

并且一言API是人多时出现异常（大约半分钟15-30次以上），正常使用时

附上使用环境liunx下使用docker搭建的koishi-4.18.3
插件版本1.0.14

**Comment by dingyi222666** [comment]
一言 API 如果用的人多，那建议先别用了。。。。
除非你能自己搭建，或者提供 RPM 高的免费 API。

另外此插件并不需要多份配置，合理的使用此插件即可实现在不同群里使用不同的欢迎信息。

![image](https://github.com/user-attachments/assets/57b43956-c5bb-480c-85c9-143d67e3d5c7)

![image](https://github.com/user-attachments/assets/d78c3169-3e3c-48ad-991b-2787739712bd)

你可以通过条件配置来在不同的群里面使用不同的欢迎信息。

**Comment by dingyi222666** [comment]
OK，知道问题在哪了，重新修复
